"""
DOCX Export Module with Professional Formatting

Professional DOCX generation with custom branding, logos, and styling.
Supports headers, footers, tables, images, and multi-level formatting.
"""

from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any, Union
import logging

logger = logging.getLogger('dms.docx')


class BrandingConfig:
    """Configuration for DOCX branding."""

    def __init__(self):
        self.company_name = "Document Management System"
        self.company_tagline = "Professional Service Management"
        self.logo_path = None  # Path to logo image
        self.primary_color = RGBColor(13, 110, 253)  # Blue
        self.secondary_color = RGBColor(108, 117, 125)  # Gray
        self.accent_color = RGBColor(25, 135, 84)  # Green
        self.header_font = 'Calibri'
        self.body_font = 'Calibri'
        self.font_size_title = 24
        self.font_size_heading1 = 18
        self.font_size_heading2 = 14
        self.font_size_body = 11
        self.footer_text = "Generated by Document Management System"
        self.show_page_numbers = True
        self.show_header = True
        self.show_footer = True


class DOCXExporter:
    """Export data to professional DOCX documents."""

    def __init__(self, branding: Optional[BrandingConfig] = None):
        """
        Initialize DOCX exporter.

        Args:
            branding: Branding configuration
        """
        self.branding = branding or BrandingConfig()
        self.doc = None

    def create_document(self, title: str = "Document") -> Document:
        """
        Create a new document with branding.

        Args:
            title: Document title

        Returns:
            Document object
        """
        self.doc = Document()
        self._setup_styles()
        self._setup_header_footer()
        return self.doc

    def _setup_styles(self):
        """Set up custom document styles."""
        styles = self.doc.styles

        # Custom Title style
        try:
            title_style = styles['Custom Title']
        except KeyError:
            title_style = styles.add_style('Custom Title', WD_STYLE_TYPE.PARAGRAPH)

        title_font = title_style.font
        title_font.name = self.branding.header_font
        title_font.size = Pt(self.branding.font_size_title)
        title_font.bold = True
        title_font.color.rgb = self.branding.primary_color
        title_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_style.paragraph_format.space_after = Pt(12)

        # Custom Heading 1
        try:
            h1_style = styles['Custom Heading 1']
        except KeyError:
            h1_style = styles.add_style('Custom Heading 1', WD_STYLE_TYPE.PARAGRAPH)

        h1_font = h1_style.font
        h1_font.name = self.branding.header_font
        h1_font.size = Pt(self.branding.font_size_heading1)
        h1_font.bold = True
        h1_font.color.rgb = self.branding.primary_color
        h1_style.paragraph_format.space_before = Pt(12)
        h1_style.paragraph_format.space_after = Pt(6)

        # Custom Heading 2
        try:
            h2_style = styles['Custom Heading 2']
        except KeyError:
            h2_style = styles.add_style('Custom Heading 2', WD_STYLE_TYPE.PARAGRAPH)

        h2_font = h2_style.font
        h2_font.name = self.branding.header_font
        h2_font.size = Pt(self.branding.font_size_heading2)
        h2_font.bold = True
        h2_font.color.rgb = self.branding.secondary_color
        h2_style.paragraph_format.space_before = Pt(8)
        h2_style.paragraph_format.space_after = Pt(4)

        # Custom Body
        try:
            body_style = styles['Custom Body']
        except KeyError:
            body_style = styles.add_style('Custom Body', WD_STYLE_TYPE.PARAGRAPH)

        body_font = body_style.font
        body_font.name = self.branding.body_font
        body_font.size = Pt(self.branding.font_size_body)
        body_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        body_style.paragraph_format.line_spacing = 1.15

    def _setup_header_footer(self):
        """Set up document header and footer."""
        if not self.doc:
            return

        # Header
        if self.branding.show_header:
            header = self.doc.sections[0].header
            header_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
            header_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT

            # Add logo if available
            if self.branding.logo_path and Path(self.branding.logo_path).exists():
                run = header_para.add_run()
                run.add_picture(self.branding.logo_path, width=Inches(1.5))

            # Add company name
            run = header_para.add_run(f"\n{self.branding.company_name}")
            run.font.size = Pt(10)
            run.font.color.rgb = self.branding.primary_color
            run.font.bold = True

        # Footer
        if self.branding.show_footer:
            footer = self.doc.sections[0].footer
            footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()

            # Footer text
            run = footer_para.add_run(
                f"{self.branding.footer_text} | {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            )
            run.font.size = Pt(8)
            run.font.color.rgb = self.branding.secondary_color

            # Page numbers
            if self.branding.show_page_numbers:
                footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = footer_para.add_run("\nPage ")
                self._add_page_number(run)

    def _add_page_number(self, run):
        """Add page number field to run."""
        fldChar1 = OxmlElement('w:fldChar')
        fldChar1.set(qn('w:fldCharType'), 'begin')

        instrText = OxmlElement('w:instrText')
        instrText.set(qn('xml:space'), 'preserve')
        instrText.text = "PAGE"

        fldChar2 = OxmlElement('w:fldChar')
        fldChar2.set(qn('w:fldCharType'), 'end')

        run._r.append(fldChar1)
        run._r.append(instrText)
        run._r.append(fldChar2)

    def add_title(self, text: str):
        """
        Add document title.

        Args:
            text: Title text
        """
        para = self.doc.add_paragraph(text, style='Custom Title')
        return para

    def add_heading(self, text: str, level: int = 1):
        """
        Add heading.

        Args:
            text: Heading text
            level: Heading level (1 or 2)
        """
        if level == 1:
            para = self.doc.add_paragraph(text, style='Custom Heading 1')
        else:
            para = self.doc.add_paragraph(text, style='Custom Heading 2')
        return para

    def add_paragraph(self, text: str, style: str = 'Custom Body'):
        """
        Add paragraph.

        Args:
            text: Paragraph text
            style: Paragraph style
        """
        para = self.doc.add_paragraph(text, style=style)
        return para

    def add_bullet_list(self, items: List[str]):
        """
        Add bullet list.

        Args:
            items: List items
        """
        for item in items:
            para = self.doc.add_paragraph(item, style='List Bullet')
            para.paragraph_format.left_indent = Inches(0.25)

    def add_numbered_list(self, items: List[str]):
        """
        Add numbered list.

        Args:
            items: List items
        """
        for item in items:
            para = self.doc.add_paragraph(item, style='List Number')
            para.paragraph_format.left_indent = Inches(0.25)

    def add_table(self, data: List[List[str]], headers: Optional[List[str]] = None,
                  style: str = 'Light Grid Accent 1'):
        """
        Add table.

        Args:
            data: Table data (list of rows)
            headers: Column headers (optional)
            style: Table style
        """
        rows = len(data) + (1 if headers else 0)
        cols = len(data[0]) if data else 0

        table = self.doc.add_table(rows=rows, cols=cols)
        table.style = style

        # Add headers
        if headers:
            header_cells = table.rows[0].cells
            for i, header in enumerate(headers):
                header_cells[i].text = header
                # Make header bold
                for para in header_cells[i].paragraphs:
                    for run in para.runs:
                        run.font.bold = True
                        run.font.color.rgb = RGBColor(255, 255, 255)

        # Add data
        start_row = 1 if headers else 0
        for i, row in enumerate(data):
            cells = table.rows[start_row + i].cells
            for j, value in enumerate(row):
                cells[j].text = str(value)

        return table

    def add_image(self, image_path: str, width: Optional[float] = None):
        """
        Add image.

        Args:
            image_path: Path to image
            width: Image width in inches (optional)
        """
        if not Path(image_path).exists():
            logger.warning(f"Image not found: {image_path}")
            return None

        para = self.doc.add_paragraph()
        run = para.add_run()

        if width:
            run.add_picture(image_path, width=Inches(width))
        else:
            run.add_picture(image_path)

        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        return para

    def add_page_break(self):
        """Add page break."""
        self.doc.add_page_break()

    def add_info_box(self, title: str, content: str):
        """
        Add highlighted info box.

        Args:
            title: Box title
            content: Box content
        """
        # Title
        para_title = self.doc.add_paragraph()
        run_title = para_title.add_run(f"💡 {title}")
        run_title.font.bold = True
        run_title.font.size = Pt(12)
        run_title.font.color.rgb = self.branding.primary_color

        # Content
        para_content = self.doc.add_paragraph(content)
        para_content.paragraph_format.left_indent = Inches(0.25)
        para_content.paragraph_format.space_after = Pt(12)

    def export_simple(self, content: str, output_path: str, title: str = "Document") -> bool:
        """
        Export simple text content to DOCX.

        Args:
            content: Document content
            output_path: Output file path
            title: Document title

        Returns:
            True if successful
        """
        try:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)

            self.create_document(title)
            self.add_title(title)

            # Process content line by line
            for line in content.split('\n'):
                line = line.strip()
                if not line:
                    continue

                # Detect headings
                if line.startswith('#'):
                    level = line.count('#', 0, 3)
                    text = line.lstrip('#').strip()
                    self.add_heading(text, min(level, 2))
                elif line.startswith('- ') or line.startswith('* '):
                    text = line[2:].strip()
                    self.add_bullet_list([text])
                else:
                    self.add_paragraph(line)

            self.doc.save(output_path)
            logger.info(f"DOCX exported successfully: {output_path}")
            return True

        except Exception as e:
            logger.error(f"DOCX export failed: {e}")
            return False

    def export_structured(self, data: Dict[str, Any], output_path: str,
                          title: str = "Document") -> bool:
        """
        Export structured data to DOCX.

        Args:
            data: Structured data dictionary
            output_path: Output file path
            title: Document title

        Returns:
            True if successful
        """
        try:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)

            self.create_document(title)
            self.add_title(title)

            # Process data
            for key, value in data.items():
                self.add_heading(str(key).replace('_', ' ').title(), level=1)

                if isinstance(value, dict):
                    # Nested dictionary
                    for sub_key, sub_value in value.items():
                        self.add_heading(str(sub_key).replace('_', ' ').title(), level=2)
                        self.add_paragraph(str(sub_value))

                elif isinstance(value, list):
                    # List
                    if value and isinstance(value[0], dict):
                        # List of dictionaries - create table
                        headers = list(value[0].keys())
                        rows = [[str(item.get(h, '')) for h in headers] for item in value]
                        self.add_table(rows, headers)
                    else:
                        # Simple list
                        self.add_bullet_list([str(item) for item in value])

                else:
                    # Simple value
                    self.add_paragraph(str(value))

            self.doc.save(output_path)
            logger.info(f"DOCX exported successfully: {output_path}")
            return True

        except Exception as e:
            logger.error(f"DOCX export failed: {e}")
            return False

    def export_report(self, report_data: Dict[str, Any], output_path: str) -> bool:
        """
        Export professional report to DOCX.

        Args:
            report_data: Report data with title, sections, etc.
            output_path: Output file path

        Returns:
            True if successful
        """
        try:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)

            title = report_data.get('title', 'Report')
            self.create_document(title)
            self.add_title(title)

            # Subtitle/Date
            subtitle = report_data.get('subtitle')
            if subtitle:
                para = self.doc.add_paragraph(subtitle)
                para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                para.paragraph_format.space_after = Pt(12)

            date = report_data.get('date', datetime.now().strftime('%Y-%m-%d'))
            para = self.doc.add_paragraph(f"Date: {date}")
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            para.paragraph_format.space_after = Pt(24)

            # Executive Summary
            if 'summary' in report_data:
                self.add_heading("Executive Summary", level=1)
                self.add_paragraph(report_data['summary'])

            # Sections
            sections = report_data.get('sections', [])
            for section in sections:
                section_title = section.get('title', 'Section')
                self.add_heading(section_title, level=1)

                content = section.get('content', '')
                if content:
                    self.add_paragraph(content)

                # Subsections
                subsections = section.get('subsections', [])
                for subsection in subsections:
                    subsection_title = subsection.get('title', 'Subsection')
                    self.add_heading(subsection_title, level=2)

                    subsection_content = subsection.get('content', '')
                    if subsection_content:
                        self.add_paragraph(subsection_content)

                    # Tables
                    if 'table' in subsection:
                        table_data = subsection['table']
                        headers = table_data.get('headers')
                        rows = table_data.get('rows', [])
                        self.add_table(rows, headers)

                    # Lists
                    if 'list' in subsection:
                        self.add_bullet_list(subsection['list'])

            # Conclusion
            if 'conclusion' in report_data:
                self.add_heading("Conclusion", level=1)
                self.add_paragraph(report_data['conclusion'])

            self.doc.save(output_path)
            logger.info(f"Report exported successfully: {output_path}")
            return True

        except Exception as e:
            logger.error(f"Report export failed: {e}")
            return False


# Convenience function
def export_to_docx(content: Union[str, Dict], output_path: str,
                   title: str = "Document", branding: Optional[BrandingConfig] = None) -> bool:
    """
    Quick export function.

    Args:
        content: Content (string or dict)
        output_path: Output path
        title: Document title
        branding: Optional branding config

    Returns:
        True if successful
    """
    exporter = DOCXExporter(branding)

    if isinstance(content, str):
        return exporter.export_simple(content, output_path, title)
    elif isinstance(content, dict):
        return exporter.export_structured(content, output_path, title)
    else:
        logger.error(f"Unsupported content type: {type(content)}")
        return False
