#!/bin/bash
# Автоматический аудит упрощений тестов

echo "🔍 Test Simplification Audit"
echo "================================"

# Параметры
COMMIT_RANGE="${1:-HEAD~20..HEAD}"
OUTPUT_FILE="test_simplification_audit_$(date +%Y%m%d_%H%M%S).md"

echo "Analyzing commits: $COMMIT_RANGE"
echo "Output file: $OUTPUT_FILE"
echo ""

# Создать отчет
cat > "$OUTPUT_FILE" << EOF
# Test Simplification Audit Report
**Date:** $(date +"%Y-%m-%d %H:%M:%S")
**Commit Range:** $COMMIT_RANGE
**Generated by:** $(whoami)

---

## Summary

EOF

# Счетчики
TOTAL_TEST_FILES_CHANGED=0
SUSPICIOUS_CHANGES=0

# Найти все измененные тестовые файлы
CHANGED_TEST_FILES=$(git diff --name-only $COMMIT_RANGE | grep "^tests/.*\.py$")

if [ -z "$CHANGED_TEST_FILES" ]; then
  echo "✅ No test files changed in this range"
  echo "No test files changed." >> "$OUTPUT_FILE"
  exit 0
fi

TOTAL_TEST_FILES_CHANGED=$(echo "$CHANGED_TEST_FILES" | wc -l)

echo "### Changed Test Files: $TOTAL_TEST_FILES_CHANGED" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Анализировать каждый файл
for TEST_FILE in $CHANGED_TEST_FILES; do
  echo "Analyzing $TEST_FILE..."

  echo "#### $TEST_FILE" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"

  # Проверка 1: pytest.raises удален
  REMOVED_RAISES=$(git diff $COMMIT_RANGE -- "$TEST_FILE" | grep "^-.*pytest\.raises" | wc -l)
  ADDED_RAISES=$(git diff $COMMIT_RANGE -- "$TEST_FILE" | grep "^+.*pytest\.raises" | wc -l)

  if [ $REMOVED_RAISES -gt $ADDED_RAISES ]; then
    echo "🔴 **SUSPICIOUS:** Removed pytest.raises" >> "$OUTPUT_FILE"
    echo "- Removed: $REMOVED_RAISES" >> "$OUTPUT_FILE"
    echo "- Added: $ADDED_RAISES" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    SUSPICIOUS_CHANGES=$((SUSPICIOUS_CHANGES + 1))
  fi

  # Проверка 2: Изменения в assert statements
  CHANGED_ASSERTS=$(git diff $COMMIT_RANGE -- "$TEST_FILE" | grep -c "^-.*assert")

  if [ $CHANGED_ASSERTS -gt 0 ]; then
    echo "⚠️  **INFO:** Changed assertions: $CHANGED_ASSERTS" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    # Показать примеры
    echo "**Examples:**" >> "$OUTPUT_FILE"
    echo '```diff' >> "$OUTPUT_FILE"
    git diff $COMMIT_RANGE -- "$TEST_FILE" | grep -A 1 "^-.*assert" | head -10 >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
  fi

  # Проверка 3: Численные изменения
  git diff $COMMIT_RANGE -- "$TEST_FILE" | grep -E "^[\-\+].*assert.*[<>]=?.*[0-9]" > /tmp/numeric_changes_$$

  if [ -s /tmp/numeric_changes_$$ ]; then
    echo "⚠️  **INFO:** Numeric assertion changes detected" >> "$OUTPUT_FILE"
    echo '```diff' >> "$OUTPUT_FILE"
    cat /tmp/numeric_changes_$$ | head -10 >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
  fi

  rm -f /tmp/numeric_changes_$$
  echo "---" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done

# Добавить итоги
cat >> "$OUTPUT_FILE" << EOF

## Statistics

- **Total test files changed:** $TOTAL_TEST_FILES_CHANGED
- **Suspicious changes found:** $SUSPICIOUS_CHANGES

## Recommendation

EOF

if [ $SUSPICIOUS_CHANGES -eq 0 ]; then
  echo "✅ **No suspicious test simplifications detected.**" >> "$OUTPUT_FILE"
  echo ""
  echo "✅ Audit complete: No issues found"
else
  echo "⚠️  **Found $SUSPICIOUS_CHANGES suspicious change(s).**" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "Please review manually and ensure changes are justified." >> "$OUTPUT_FILE"
  echo ""
  echo "⚠️  Audit complete: $SUSPICIOUS_CHANGES issue(s) found"
fi

echo ""
echo "Report saved to: $OUTPUT_FILE"
echo ""
echo "To view: cat $OUTPUT_FILE"
